services:
  frontend:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./frontend:/usr/share/nginx/html
  api:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app